# root
GET http://localhost:5000/
###
GET http://localhost:5000/blackFriday?field=async
###

GET http://localhost:5000/blackFriday?field=callback
###

GET http://localhost:5000/blackFriday?field=promise
###

PUT http://localhost:5000/uploadcsv HTTP/1.1
Content-Type: application/gzip

< med_sample.csv.gz
###

GET http://localhost:5000/listOfFiles
###

PUT http://localhost:5000/uploadcsv HTTP/1.1
Content-Type: application/gzip

< products.csv.gz
###

PUT http://localhost:5000/optimize/VItS_BdPmUVFwWZlpj403.json