# root
GET http://localhost:5000/
Authorization:Basic TWFzdGVyczpBY2FkZW15
###
PUT http://localhost:5000/newJson HTTP/1.1
Authorization:Basic TWFzdGVyczpBY2FkZW15

content-type: application/json

[
  {"type": "socks", "color": "red", "quantity": 10, "priceForPair": "$3"},
  {"type": "socks", "color": "green", "quantity": 5, "priceForPair": "$10"},

]
###

GET http://localhost:5000/blackfriday/async
Authorization:Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:5000/blackfriday/clbck
Authorization:Basic TWFzdGVyczpBY2FkZW15
###

GET http://localhost:5000/blackfriday/prmss
Authorization:Basic TWFzdGVyczpBY2FkZW15
###

### SMALL FILE
PUT http://localhost:5000/uploadcsv HTTP/1.1
Authorization: Basic TWFzdGVyczpBY2FkZW15

< med_sample.csv.gz

### LARGE FILE
PUT http://localhost:5000/uploadcsv HTTP/1.1
Authorization:Basic TWFzdGVyczpBY2FkZW15

< products.csv.gz

### OPTIMIZE
POST http://localhost:5000/optimize/products.json
Authorization:Basic TWFzdGVyczpBY2FkZW15

### LIST
GET http://localhost:5000/upload/listOfFiles
Authorization:Basic TWFzdGVyczpBY2FkZW15

### PUSH DB
POST http://localhost:5000/push_db/opt-products.json
Authorization:Basic TWFzdGVyczpBY2FkZW15

### CREATE NEW ELEMENT IN DB
POST http://localhost:5000/create?type=boots&color=white&price=123
Authorization:Basic TWFzdGVyczpBY2FkZW15